name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Code Style
        run: |          
          python -m pylint $(git ls-files '*.py')
      - name: MyPy check
        run: |
          python -m mypy $(git ls-files '*.py')
      - name: Flake8 check
        run: |
          python -m flake8 $(git ls-files '*.py')
      - name: Doc8 check
        run: |
          python -m doc8 $(git ls-files '*.py')
      - name: Tests
        run: |
          python -m pytest tests