name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MyPy check
        run: |
          python -m mypy $(git ls-files '*.py') --ignore-missing-imports --show-column-numbers 

      - name: Doc8 check
        run: |
          python -m doc8 $(git ls-files '*.py') --max-line-length=120

      - name: Tests
        run: |
          python -m pytest tests --maxfail=5 --disable-warnings --verbose

      - name: Flake8 check
        run: |
          python -m flake8 $(git ls-files '*.py') --max-line-length=120 --extend-ignore=E203,W503


